services:
  memos:
    image: neosmemo/memos:0.25.1
    container_name: memos
    volumes:
      - /home/ubuntu/light/memos/.memos:/var/opt/memos
    ports:
      - "5230:5230"

  mortis:
    image: ghcr.io/mudkipme/mortis:0.25.1
    container_name: mortis
    ports:
      - "5231:5231"
    entrypoint: [ "/app/mortis" ]
    command: [ "-grpc-addr=memos:5230" ]
    depends_on:
      - memos
