server {
        listen 80;
        server_name _;
        access_log /var/log/nginx/memos.log;
        error_log  /var/log/nginx/memos.error.log;
        client_max_body_size 200M;
        location = /admin {
                return 302 /admin/;
        }

        location /admin/ {
                proxy_pass http://127.0.0.1:3000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_connect_timeout 600s;
                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
                proxy_buffer_size 64k;
                proxy_buffers 4 128k;
                proxy_busy_buffers_size 256k;
        }

        location / {
                proxy_pass http://127.0.0.1:5230/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}