name: zeabure memos backup

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点UTC执行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'  # 使用适合你的Python版本

      - name: Install dependencies
        run: |
          cd src
          pip install -r requirements.txt

      - name: Run Python script
        env: # Or as an environment variable
          ZEABURE_PROJECTID: ${{ vars.ZEABURE_PROJECTID  }}
          ZEABURE_SERVICEID: ${{ vars.ZEABURE_SERVICEID  }}
          ZEABURE_ENVID: ${{ vars.ZEABURE_ENVID  }}
          MAIL_126_PASSWORD: ${{ vars.MAIL_126_PASSWORD  }}
        run: |
          cd src
          python main.py

      - name: Commit changes to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git status
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git push --force
          fi